# Generated by Django 2.1.2 on 2018-10-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181019_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
