# Generated by Django 2.1.2 on 2018-10-20 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_head_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='head_img',
        ),
    ]
